# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: ["master"]

jobs:
  build:
    permissions:
      contents: write
      actions: write
      attestations: write
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build
        run: go build -v ./...

      - name: Upload archive
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.release_url }}
          asset_path: hivemind
          asset_name: hivemind-${{ needs.create_release.outputs.version_number }}-linux
          asset_content_type: application/vnd.microsoft.portable-executable

        # TODO: tests
        # DONE: release packaging
