# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["master"]

jobs:
  create_release:
    permissions:
      contents: write
      actions: write
      attestations: write
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.versionnum.outputs.version.outputs.tag }}
      release_url: ${{steps.create_release.outputs.upload_url}}
      version_number: ${{steps.versionnum.outputs.version}}
      semantic_version: ${{steps.versionvnum.outputs.v_version}}
    steps:
      - uses: actions/checkout@master
      - name: Get Version Number
        id: versionnum
        run: |
          echo "version=$(cat Version.props | grep -oP '(?<=<Version>).*?(?=</Version>)')" >> $GITHUB_OUTPUT

      - name: Concatenate 'v'
        id: versionvnum
        run: |
          echo "v_version=$(printf "v%s" ${{ steps.versionnum.outputs.version }})" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.versionnum.outputs.version }}
          release_name: ${{ steps.versionvnum.outputs.v_version}}
          draft: false
          prerelease: false
  build:
    permissions:
      contents: write
      actions: write
      attestations: write
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build
        run: go build -v ./...

      - name: Upload archive
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.release_url }}
          asset_path: hivemind
          asset_name: hivemind-${{ needs.create_release.outputs.version_number }}-linux
          asset_content_type: application/vnd.microsoft.portable-executable

        # TODO: tests
        # TODO: release packaging
